"""remove unique constraint from created_by_id

Revision ID: 9b9f64526a37
Revises: f1eaed4c4fa1
Create Date: 2026-06-17 11:21:24.729168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9f64526a37'
down_revision: Union[str, Sequence[str], None] = 'f1eaed4c4fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('places_created_by_id_key'), 'places', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('places_created_by_id_key'), 'places', ['created_by_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
